// DO NOT EDIT: this file is automatically generated by docgen
package metalcloud

import (
	"github.com/projectdiscovery/yamldoc-go/encoder"
)

var DatacenterDoc encoder.Doc

func init() {
	DatacenterDoc.Type = "Datacenter"
	DatacenterDoc.Comments[encoder.LineComment] = "Datacenter"
	DatacenterDoc.Description = "Datacenter"
	DatacenterDoc.Fields = make([]encoder.Doc, 0)
}

func (Datacenter) Doc() *encoder.Doc {
	return &DatacenterDoc
}

// GetDatacenterDoc returns documentation for the file ./.
func GetDatacenterDoc() *encoder.FileDoc {
	return &encoder.FileDoc{
		Name:        "Datacenter",
		Description: "",
		Structs: []*encoder.Doc{
			&DatacenterDoc,
		},
	}
}
