// Code generated by gen_exports.go DO NOT EDIT

package metalcloud

//DriveArrayCreate array. Requires deploy.
func (c *Client) DriveArrayCreate(infrastructureID int, driveArray DriveArray) (*DriveArray, error) {
	return c.driveArrayCreate(infrastructureID,driveArray)
}

//DriveArrayCreateByLabel array. Requires deploy.
func (c *Client) DriveArrayCreateByLabel(infrastructureLabel string, driveArray DriveArray) (*DriveArray, error) {
	return c.driveArrayCreate(infrastructureLabel,driveArray)
}

//DriveArrayEdit array. Requires deploy.
func (c *Client) DriveArrayEdit(driveArrayID int, driveArrayOperation DriveArrayOperation) (*DriveArray, error) {
	return c.driveArrayEdit(driveArrayID,driveArrayOperation)
}

//DriveArrayEditByLabel array. Requires deploy.
func (c *Client) DriveArrayEditByLabel(driveArrayLabel string, driveArrayOperation DriveArrayOperation) (*DriveArray, error) {
	return c.driveArrayEdit(driveArrayLabel,driveArrayOperation)
}

//DriveArrayDelete 
func (c *Client) DriveArrayDelete(driveArrayID int) error {
	return c.driveArrayDelete(driveArrayID)
}

//DriveArrayDeleteByLabel 
func (c *Client) DriveArrayDeleteByLabel(driveArrayLabel string) error {
	return c.driveArrayDelete(driveArrayLabel)
}

//DriveArrayDrives 
func (c *Client) DriveArrayDrives(driveArray int) (*map[string]Drive, error) {
	return c.driveArrayDrives(driveArray)
}

//DriveArrayDrivesByLabel 
func (c *Client) DriveArrayDrivesByLabel(driveArrLabel string) (*map[string]Drive, error) {
	return c.driveArrayDrives(driveArrLabel)
}
