// Code generated by gen_exports.go DO NOT EDIT

package metalcloud

// ExternalConnectionGet
func (c *Client) ExternalConnectionGet(externalConnectionID int) (*ExternalConnection, error) {
	return c.externalConnectionGet(externalConnectionID)
}

// ExternalConnectionGetByLabel
func (c *Client) ExternalConnectionGetByLabel(externalConnectionLabel string) (*ExternalConnection, error) {
	return c.externalConnectionGet(externalConnectionLabel)
}

// ExternalConnectionEdit connection.
func (c *Client) ExternalConnectionEdit(externalConnectionID int, externalConnection ExternalConnection) (*ExternalConnection, error) {
	return c.externalConnectionEdit(externalConnectionID, externalConnection)
}

// ExternalConnectionEditByLabel connection.
func (c *Client) ExternalConnectionEditByLabel(externalConnectionLabel string, externalConnection ExternalConnection) (*ExternalConnection, error) {
	return c.externalConnectionEdit(externalConnectionLabel, externalConnection)
}

// ExternalConnectionDelete connection.
func (c *Client) ExternalConnectionDelete(externalConnectionID int) error {
	return c.externalConnectionDelete(externalConnectionID)
}

// ExternalConnectionDeleteByLabel connection.
func (c *Client) ExternalConnectionDeleteByLabel(externalConnectionLabel string) error {
	return c.externalConnectionDelete(externalConnectionLabel)
}
