// Code generated by gen_exports.go DO NOT EDIT

package metalcloud

//ExternalConnectionGet returns an external connection with specified id
func (c *Client) ExternalConnectionGet(externalConnectionID int) (*ExternalConnection, error) {
	return c.externalConnectionGet(externalConnectionID)
}

//ExternalConnectionGetByLabel returns an external connection with specified id
func (c *Client) ExternalConnectionGetByLabel(externalConnectionLabel string) (*ExternalConnection, error) {
	return c.externalConnectionGet(externalConnectionLabel)
}

//ExternalConnectionEdit updates an external connection.
func (c *Client) ExternalConnectionEdit(externalConnectionID int, externalConnection ExternalConnection) (*ExternalConnection, error) {
	return c.externalConnectionEdit(externalConnectionID,externalConnection)
}

//ExternalConnectionEditByLabel updates an external connection.
func (c *Client) ExternalConnectionEditByLabel(externalConnectionLabel string, externalConnection ExternalConnection) (*ExternalConnection, error) {
	return c.externalConnectionEdit(externalConnectionLabel,externalConnection)
}

//ExternalConnectionDelete deletes an external connection.
func (c *Client) ExternalConnectionDelete(externalConnectionID int) error {
	return c.externalConnectionDelete(externalConnectionID)
}

//ExternalConnectionDeleteByLabel deletes an external connection.
func (c *Client) ExternalConnectionDeleteByLabel(externalConnectionLabel string) error {
	return c.externalConnectionDelete(externalConnectionLabel)
}
