// Code generated by gen_exports.go DO NOT EDIT

package metalcloud

//InstanceArrayGet returns an InstanceArray with specified id
func (c *Client) InstanceArrayGet(instanceArrayID int) (*InstanceArray, error) {
	return c.instanceArrayGet(instanceArrayID)
}

//InstanceArrayGetByLabel returns an InstanceArray with specified id
func (c *Client) InstanceArrayGetByLabel(instanceArrayLabel string) (*InstanceArray, error) {
	return c.instanceArrayGet(instanceArrayLabel)
}

//InstanceArrays returns list of instance arrays of specified infrastructure
func (c *Client) InstanceArrays(infrastructureID int) (*map[string]InstanceArray, error) {
	return c.instanceArrays(infrastructureID)
}

//InstanceArraysByLabel returns list of instance arrays of specified infrastructure
func (c *Client) InstanceArraysByLabel(infrastructureLabel string) (*map[string]InstanceArray, error) {
	return c.instanceArrays(infrastructureLabel)
}

//InstanceArrayCreate creates an instance array (colletion of identical instances). Requires Deploy.
func (c *Client) InstanceArrayCreate(infrastructureID int, instanceArray InstanceArray) (*InstanceArray, error) {
	return c.instanceArrayCreate(infrastructureID,instanceArray)
}

//InstanceArrayCreateByLabel creates an instance array (colletion of identical instances). Requires Deploy.
func (c *Client) InstanceArrayCreateByLabel(infrastructureLabel string, instanceArray InstanceArray) (*InstanceArray, error) {
	return c.instanceArrayCreate(infrastructureLabel,instanceArray)
}

//InstanceArrayEdit alterns a deployed instance array. Requires deploy.
func (c *Client) InstanceArrayEdit(instanceArrayID int, instanceArrayOperation InstanceArrayOperation, bSwapExistingInstancesHardware *bool, bKeepDetachingDrives *bool, objServerTypeMatches *[]ServerType, arrInstancesToBeDeleted *[]int) (*InstanceArray, error) {
	return c.instanceArrayEdit(instanceArrayID,instanceArrayOperation,bSwapExistingInstancesHardware,bKeepDetachingDrives,objServerTypeMatches,arrInstancesToBeDeleted)
}

//InstanceArrayEditByLabel alterns a deployed instance array. Requires deploy.
func (c *Client) InstanceArrayEditByLabel(instanceArrayLabel string, instanceArrayOperation InstanceArrayOperation, bSwapExistingInstancesHardware *bool, bKeepDetachingDrives *bool, objServerTypeMatches *[]ServerType, arrInstancesToBeDeleted *[]int) (*InstanceArray, error) {
	return c.instanceArrayEdit(instanceArrayLabel,instanceArrayOperation,bSwapExistingInstancesHardware,bKeepDetachingDrives,objServerTypeMatches,arrInstancesToBeDeleted)
}

//InstanceArrayDelete deletes an instance array. Requires deploy.
func (c *Client) InstanceArrayDelete(instanceArrayID int) error {
	return c.instanceArrayDelete(instanceArrayID)
}

//InstanceArrayDeleteByLabel deletes an instance array. Requires deploy.
func (c *Client) InstanceArrayDeleteByLabel(instanceArrayLabel string) error {
	return c.instanceArrayDelete(instanceArrayLabel)
}
