// Code generated by gen_exports.go DO NOT EDIT

package metalcloud

//InstanceEdit instance. Requires deploy
func (c *Client) InstanceEdit(instanceID int, instanceOperation InstanceOperation) (*Instance, error) {
	return c.instanceEdit(instanceID,instanceOperation)
}

//InstanceEditByLabel instance. Requires deploy
func (c *Client) InstanceEditByLabel(instanceLabel string, instanceOperation InstanceOperation) (*Instance, error) {
	return c.instanceEdit(instanceLabel,instanceOperation)
}

//InstanceArrayInstances InstanceArray.
func (c *Client) InstanceArrayInstances(instanceArrayID int) (*map[string]Instance, error) {
	return c.instanceArrayInstances(instanceArrayID)
}

//InstanceArrayInstancesByLabel InstanceArray.
func (c *Client) InstanceArrayInstancesByLabel(instanceArrayLabel string) (*map[string]Instance, error) {
	return c.instanceArrayInstances(instanceArrayLabel)
}

//InstanceGet 
func (c *Client) InstanceGet(instanceID int) (*Instance, error) {
	return c.instanceGet(instanceID)
}

//InstanceGetByLabel 
func (c *Client) InstanceGetByLabel(instanceLabel string) (*Instance, error) {
	return c.instanceGet(instanceLabel)
}

//InstanceServerPowerSet 
func (c *Client) InstanceServerPowerSet(instanceID int, operation string) error {
	return c.instanceServerPowerSet(instanceID,operation)
}

//InstanceServerPowerSetByLabel 
func (c *Client) InstanceServerPowerSetByLabel(instanceLabel string, operation string) error {
	return c.instanceServerPowerSet(instanceLabel,operation)
}

//InstanceServerPowerGet 
func (c *Client) InstanceServerPowerGet(instanceID int) (*string, error) {
	return c.instanceServerPowerGet(instanceID)
}

//InstanceServerPowerGetByLabel 
func (c *Client) InstanceServerPowerGetByLabel(instanceLabel string) (*string, error) {
	return c.instanceServerPowerGet(instanceLabel)
}

//InstanceServerPowerGetBatch 
func (c *Client) InstanceServerPowerGetBatch(infrastructureID int, instanceIDs []int) (*map[string]string, error) {
	return c.instanceServerPowerGetBatch(infrastructureID,instanceIDs)
}

//InstanceServerPowerGetBatchByLabel 
func (c *Client) InstanceServerPowerGetBatchByLabel(infrastructureLabel string, instanceIDs []int) (*map[string]string, error) {
	return c.instanceServerPowerGetBatch(infrastructureLabel,instanceIDs)
}
