// Code generated by gen_exports.go DO NOT EDIT

package metalcloud

//ClusterCreate 
func (c *Client) ClusterCreate(infrastructureID int, cluster Cluster) (*Cluster, error) {
	return c.clusterCreate(infrastructureID,cluster)
}

//ClusterCreateByLabel 
func (c *Client) ClusterCreateByLabel(infrastructureLabel string, cluster Cluster) (*Cluster, error) {
	return c.clusterCreate(infrastructureLabel,cluster)
}

//ClusterGet (app) with specified id
func (c *Client) ClusterGet(clusterID int) (*Cluster, error) {
	return c.clusterGet(clusterID)
}

//ClusterGetByLabel (app) with specified id
func (c *Client) ClusterGetByLabel(clusterLabel string) (*Cluster, error) {
	return c.clusterGet(clusterLabel)
}

//ClusterAppVMWareVSphere 
func (c *Client) ClusterAppVMWareVSphere(clusterID int, decryptCredentials bool) (*AppVMWareVsphere, error) {
	return c.clusterAppVMWareVSphere(clusterID,decryptCredentials)
}

//ClusterAppVMWareVSphereByLabel 
func (c *Client) ClusterAppVMWareVSphereByLabel(clusterLabel string, decryptCredentials bool) (*AppVMWareVsphere, error) {
	return c.clusterAppVMWareVSphere(clusterLabel,decryptCredentials)
}

//ClusterAppKubernetes 
func (c *Client) ClusterAppKubernetes(clusterID int, decryptCredentials bool) (*AppKubernetes, error) {
	return c.clusterAppKubernetes(clusterID,decryptCredentials)
}

//ClusterAppKubernetesByLabel 
func (c *Client) ClusterAppKubernetesByLabel(clusterLabel string, decryptCredentials bool) (*AppKubernetes, error) {
	return c.clusterAppKubernetes(clusterLabel,decryptCredentials)
}

//ClusterDelete array. Requires deploy.
func (c *Client) ClusterDelete(clusterID int) error {
	return c.clusterDelete(clusterID)
}

//ClusterDeleteByLabel array. Requires deploy.
func (c *Client) ClusterDeleteByLabel(clusterLabel string) error {
	return c.clusterDelete(clusterLabel)
}

//ClusterEdit array. Requires deploy.
func (c *Client) ClusterEdit(clusterId int, clusterOperation ClusterOperation) (*Cluster, error) {
	return c.clusterEdit(clusterId,clusterOperation)
}

//ClusterEditByLabel array. Requires deploy.
func (c *Client) ClusterEditByLabel(clusterLabel string, clusterOperation ClusterOperation) (*Cluster, error) {
	return c.clusterEdit(clusterLabel,clusterOperation)
}

//Clusters 
func (c *Client) Clusters(infrastructureId int) (*map[string]Cluster, error) {
	return c.clusters(infrastructureId)
}

//ClustersByLabel 
func (c *Client) ClustersByLabel(infrastructureLabel string) (*map[string]Cluster, error) {
	return c.clusters(infrastructureLabel)
}

//ClusterInstanceArrays 
func (c *Client) ClusterInstanceArrays(clusterId int) (*map[string]InstanceArray, error) {
	return c.clusterInstanceArrays(clusterId)
}

//ClusterInstanceArraysByLabel 
func (c *Client) ClusterInstanceArraysByLabel(clusterLabel string) (*map[string]InstanceArray, error) {
	return c.clusterInstanceArrays(clusterLabel)
}
