// Code generated by gen_exports.go DO NOT EDIT

package metalcloud

//InstanceArrayInstances retrieves a list of all the Instance objects associated with a specified InstanceArray.
func (c *Client) InstanceArrayInstances(instanceArrayID int) (*map[string]Instance, error) {
	return c.instanceArrayInstances(instanceArrayID)
}

//InstanceArrayInstancesByLabel retrieves a list of all the Instance objects associated with a specified InstanceArray.
func (c *Client) InstanceArrayInstancesByLabel(instanceArrayLabel string) (*map[string]Instance, error) {
	return c.instanceArrayInstances(instanceArrayLabel)
}

//InstanceGet returns a specific instance by id
func (c *Client) InstanceGet(instanceID int) (*Instance, error) {
	return c.instanceGet(instanceID)
}

//InstanceGetByLabel returns a specific instance by id
func (c *Client) InstanceGetByLabel(instanceLabel string) (*Instance, error) {
	return c.instanceGet(instanceLabel)
}
