// Code generated by gen_exports.go DO NOT EDIT

package metalcloud

//NetworkProfileGet returns a NetworkProfile with specified id
func (c *Client) NetworkProfileGet(networkProfileID int) (*NetworkProfile, error) {
	return c.NetworkProfileGet(networkProfileID)
}

//NetworkProfileGetByLabel returns a NetworkProfile with specified id
func (c *Client) NetworkProfileGetByLabel(networkProfileLabel string) (*NetworkProfile, error) {
	return c.NetworkProfileGet(networkProfileLabel)
}

//NetworkProfileUpdate updates a network profile.
func (c *Client) NetworkProfileUpdate(networkProfileID int, networkProfile NetworkProfile) (*NetworkProfile, error) {
	return c.NetworkProfileUpdate(networkProfileID,networkProfile)
}

//NetworkProfileUpdateByLabel updates a network profile.
func (c *Client) NetworkProfileUpdateByLabel(networkProfileLabel string, networkProfile NetworkProfile) (*NetworkProfile, error) {
	return c.NetworkProfileUpdate(networkProfileLabel,networkProfile)
}

//NetworkProfileDelete deletes a network profile.
func (c *Client) NetworkProfileDelete(networkProfileID int) error {
	return c.NetworkProfileDelete(networkProfileID)
}

//NetworkProfileDeleteByLabel deletes a network profile.
func (c *Client) NetworkProfileDeleteByLabel(networkProfileLabel string) error {
	return c.NetworkProfileDelete(networkProfileLabel)
}
