// Code generated by gen_exports.go DO NOT EDIT

package metalcloud

//NetworkProfileGet 
func (c *Client) NetworkProfileGet(networkProfileID int) (*NetworkProfile, error) {
	return c.networkProfileGet(networkProfileID)
}

//NetworkProfileGetByLabel 
func (c *Client) NetworkProfileGetByLabel(networkProfileLabel string) (*NetworkProfile, error) {
	return c.networkProfileGet(networkProfileLabel)
}

//NetworkProfileUpdate profile.
func (c *Client) NetworkProfileUpdate(networkProfileID int, networkProfile NetworkProfile) (*NetworkProfile, error) {
	return c.networkProfileUpdate(networkProfileID,networkProfile)
}

//NetworkProfileUpdateByLabel profile.
func (c *Client) NetworkProfileUpdateByLabel(networkProfileLabel string, networkProfile NetworkProfile) (*NetworkProfile, error) {
	return c.networkProfileUpdate(networkProfileLabel,networkProfile)
}

//NetworkProfileDelete profile.
func (c *Client) NetworkProfileDelete(networkProfileID int) error {
	return c.networkProfileDelete(networkProfileID)
}

//NetworkProfileDeleteByLabel profile.
func (c *Client) NetworkProfileDeleteByLabel(networkProfileLabel string) error {
	return c.networkProfileDelete(networkProfileLabel)
}
