// Code generated by gen_exports.go DO NOT EDIT

package metalcloud

//ServerTypeGet retrieves a server type by id
func (c *Client) ServerTypeGet(serverTypeID int) (*ServerType, error) {
	return c.serverTypeGet(serverTypeID)
}

//ServerTypeGetByLabel retrieves a server type by id
func (c *Client) ServerTypeGetByLabel(serverTypeLabel string) (*ServerType, error) {
	return c.serverTypeGet(serverTypeLabel)
}

//ServerTypesMatches matches available servers with a certain Instance&#39;s configuration, using the properties specified in the objHardwareConfiguration object, and returns the number of compatible servers for each server_type_id.
func (c *Client) ServerTypesMatches(infrastructureID int, hardwareConfiguration HardwareConfiguration, instanceArrayID *int, bAllowServerSwap bool) (*map[string]ServerType, error) {
	return c.serverTypesMatches(infrastructureID,hardwareConfiguration,instanceArrayID,bAllowServerSwap)
}

//ServerTypesMatchesByLabel matches available servers with a certain Instance&#39;s configuration, using the properties specified in the objHardwareConfiguration object, and returns the number of compatible servers for each server_type_id.
func (c *Client) ServerTypesMatchesByLabel(infrastructureLabel string, hardwareConfiguration HardwareConfiguration, instanceArrayID *int, bAllowServerSwap bool) (*map[string]ServerType, error) {
	return c.serverTypesMatches(infrastructureLabel,hardwareConfiguration,instanceArrayID,bAllowServerSwap)
}
