// Code generated by gen_exports.go DO NOT EDIT

package metalcloud

//VolumeTemplateGet returns the specified volume template
func (c *Client) VolumeTemplateGet(volumeTemplateID int) (*VolumeTemplate, error) {
	return c.volumeTemplateGet(volumeTemplateID)
}

//VolumeTemplateGetByLabel returns the specified volume template
func (c *Client) VolumeTemplateGetByLabel(volumeTemplateLabel string) (*VolumeTemplate, error) {
	return c.volumeTemplateGet(volumeTemplateLabel)
}
